### ISSUE TITLE
Missing declaration for use of non-medcom defined extensions

### ISSUE THREAD

**Issue by jkiddo** [medcomdk/dk-medcom-carecommunication#61]
Given that a care communication message is sent in FHIR format and that it downstream is converted using the VANS services, what can then be expected for non-medcom declared FHIR extensions in the converted format?

**Comment by tmsMedcom** [comment]
Only the elements in a CareCommunication marked with MustSupport should be expected to be converted, due to limitations in the (X)DIS91. So non-MedCom FHIR extensions will not be converted. 

We can add that to the documentation for the conversion service.

**Comment by jkiddo** [comment]
But the XDIS91 allows an xs:any(element) IIRC. How does that fit together?

**Comment by tmsMedcom** [comment]
Can you please point it out? https://svn.medcom.dk/svn/releases/Standarder/Den%20gode%20korrespondance/ I haven't seen it in the existing XDIS91 standard and I'm not sure vendors supports the element.

**Comment by jkiddo** [comment]
https://svn.medcom.dk/svn/drafts/Konverter/trunk/Konverter/xml/Schemas/2006/07/01/EMessage.xsd - line 19.

**Comment by jkiddo** [comment]
If I read the schema correct - they would have to support it.

**Comment by tmsMedcom** [comment]
I just consulted my colleagues. The xml tag names "LocalElements" is only an element in the XDS for OIOXML (XDIS91), not the EDIFACT (DIS91) - so you will run into problems mapping between the two, and the LocalElements is not a part of the standard. Further, the LocalElements are only used if there is an agreement between the sending and receiving part, if there isn't an agreement systems must be able to read the messages without failing if LocalElements is included, but are not required to load in the information in LocalElements (see page 12 http://svn.medcom.dk/svn/releases/Standarder/Syntaks%20og%20kommunikationsregler/XML/Dokumentation/).

**Comment by jkiddo** [comment]
how does that apply to the services that are to convert between EDI/XML and FHIR?

**Comment by tmsMedcom** [comment]
Self-defined FHIR extension will not be converted to OIOXML, and LocalElements in an OIOXML will not be converted to FHIR.

**Comment by jkiddo** [comment]
ok
